---- Name section in docker run command become dictionary.
---example docker run -d --name=redis redis here redis name would become dictionary
--- image name become value and key in each dictionary like key=image and value=image name
--- Ports would be another key and value field in appropriate section.
--- Links provide with property and array
-- run docker compose up command to build the entire application stack
-- Insted of image we have choosen build if content is available in local machine to build.
version: 2
services:
  redis:
    image: redis
    networks:
      - back-end
  db:
    image: postgres:9.4
    networks:
      - back-end
  vote:
    image: voting-app
    ports:
      - 5000:80
    networks:
      - front-end
      - back-end
    depends_on:
      - redis
  result:
    image: result-app
    ports:
      - 5001:80
    networks:
      - front-end
      - back-end
    depends_on:
      - db
  worker:
    image: worker
    networks:
      - back-end

networks:
  front-end:
  back-end:
